name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm install
      - name: Run Tests
        run: npx jest src/app/service